### PR TITLE
Added a script for the galaxy list canonicalization

### PR DESCRIPTION
**Pull request by J-E-Kennedy**
Added a script for issue #16, takes all files in a folder given as the first command line argument, and creates a file containing each unique item across any of the files. Can take an optional second argument for where the new file should be created, otherwise creates it where the script is located.

### CODE REVIEW

**Comment by michaelmunje** [comment]
Good that you have a script, but we want this to be designed as a python module function.

So essentially, you would create a properly titled main function and throw exceptions instead of printing the error.

**Review by michaelmunje — CHANGES_REQUESTED** [review]
See above

**Review by michaelmunje — CHANGES_REQUESTED** [review]
Definitely good work. 

All I would say to add is a simple unit test in the tests directory. Make a new file similar to the other ones, and have some directory which contains text files a, b, and c where c = f(a, b) and f is your function. This simply ensures your function works as expected.

**Review by gRichardson108 — CHANGES_REQUESTED** [review]
Hey just one little nitpick I noticed.

You concatenate the output_path and output_file on line 17. On Windows, the backslash separator is correct, but Linux uses forward slashe. To make it easy for the script to be compatible on both, you could use os.path.join to concatenate the pathname.

See here: https://docs.python.org/3/library/os.path.html#os.path.join

**Pull request merged**
